INSERT INTO recruitment.job_application_status (id,"name",description) VALUES
	 (1,'PENDING_APPROVAL','Pendiente de aprobación'),
	 (2,'APPROVED','Aprobado'),
	 (3,'PUBLISHED','Publicado'),
	 (4,'DECLINED','Rechazado');
	 
INSERT INTO recruitment.requirement_type (id,"name",description) VALUES
	 (1,'GLOBAL','Global'),
	 (2,'MANDATORY','Excluyente'),
	 (3,'PREFERRED','Deseable');

INSERT INTO recruitment."role" (id,"name",description) VALUES
	 (1,'RECRUITER','Recruiter'),
	 (2,'CANDIDATE','Candidate');
	 
INSERT INTO recruitment.job_application_period (id,code,description) VALUES
	 (1,'FIRST_SEMESTER','1er semestre'),
	 (2,'SECOND_SEMESTER','2do semestre'),
	 (3,'FIRST_QUARTER','1er cuatrimestre'),
	 (4,'SECOND_QUARTER','2do cuatrimestre');

INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Afghanistan', 'AF', 'AFG', '004');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Albania', 'AL', 'ALB', '008');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Algeria', 'DZ', 'DZA', '012');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('American Samoa', 'AS', 'ASM', '016');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Andorra', 'AD', 'AND', '020');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Angola', 'AO', 'AGO', '024');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Anguilla', 'AI', 'AIA', '660');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Antarctica', 'AQ', 'ATA', '010');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Antigua and Barbuda', 'AG', 'ATG', '028');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Argentina', 'AR', 'ARG', '032');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Armenia', 'AM', 'ARM', '051');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Aruba', 'AW', 'ABW', '533');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Australia', 'AU', 'AUS', '036');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Austria', 'AT', 'AUT', '040');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Azerbaijan', 'AZ', 'AZE', '031');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bahamas (the)', 'BS', 'BHS', '044');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bahrain', 'BH', 'BHR', '048');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bangladesh', 'BD', 'BGD', '050');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Barbados', 'BB', 'BRB', '052');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Belarus', 'BY', 'BLR', '112');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Belgium', 'BE', 'BEL', '056');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Belize', 'BZ', 'BLZ', '084');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Benin', 'BJ', 'BEN', '204');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bermuda', 'BM', 'BMU', '060');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bhutan', 'BT', 'BTN', '064');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bolivia (Plurinational State of)', 'BO', 'BOL', '068');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '535');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', '070');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Botswana', 'BW', 'BWA', '072');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bouvet Island', 'BV', 'BVT', '074');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Brazil', 'BR', 'BRA', '076');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('British Indian Ocean Territory (the)', 'IO', 'IOT', '086');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Brunei Darussalam', 'BN', 'BRN', '096');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Bulgaria', 'BG', 'BGR', '100');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Burkina Faso', 'BF', 'BFA', '854');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Burundi', 'BI', 'BDI', '108');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cabo Verde', 'CV', 'CPV', '132');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cambodia', 'KH', 'KHM', '116');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cameroon', 'CM', 'CMR', '120');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Canada', 'CA', 'CAN', '124');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cayman Islands (the)', 'KY', 'CYM', '136');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Central African Republic (the)', 'CF', 'CAF', '140');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Chad', 'TD', 'TCD', '148');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Chile', 'CL', 'CHL', '152');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('China', 'CN', 'CHN', '156');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Christmas Island', 'CX', 'CXR', '162');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cocos (Keeling) Islands (the)', 'CC', 'CCK', '166');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Colombia', 'CO', 'COL', '170');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Comoros (the)', 'KM', 'COM', '174');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Congo (the Democratic Republic of the)', 'CD', 'COD', '180');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Congo (the)', 'CG', 'COG', '178');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cook Islands (the)', 'CK', 'COK', '184');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Costa Rica', 'CR', 'CRI', '188');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Croatia', 'HR', 'HRV', '191');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cuba', 'CU', 'CUB', '192');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Curaçao', 'CW', 'CUW', '531');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Cyprus', 'CY', 'CYP', '196');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Czechia', 'CZ', 'CZE', '203');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Denmark', 'DK', 'DNK', '208');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Djibouti', 'DJ', 'DJI', '262');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Dominica', 'DM', 'DMA', '212');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Dominican Republic (the)', 'DO', 'DOM', '214');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Ecuador', 'EC', 'ECU', '218');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Egypt', 'EG', 'EGY', '818');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('El Salvador', 'SV', 'SLV', '222');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', '226');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Eritrea', 'ER', 'ERI', '232');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Estonia', 'EE', 'EST', '233');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Eswatini', 'SZ', 'SWZ', '748');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Ethiopia', 'ET', 'ETH', '231');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Falkland Islands (the) [Malvinas]', 'FK', 'FLK', '238');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Faroe Islands (the)', 'FO', 'FRO', '234');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Fiji', 'FJ', 'FJI', '242');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Finland', 'FI', 'FIN', '246');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('France', 'FR', 'FRA', '250');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('French Guiana', 'GF', 'GUF', '254');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('French Polynesia', 'PF', 'PYF', '258');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('French Southern Territories (the)', 'TF', 'ATF', '260');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Gabon', 'GA', 'GAB', '266');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Gambia (the)', 'GM', 'GMB', '270');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Georgia', 'GE', 'GEO', '268');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Germany', 'DE', 'DEU', '276');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Ghana', 'GH', 'GHA', '288');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Gibraltar', 'GI', 'GIB', '292');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Greece', 'GR', 'GRC', '300');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Greenland', 'GL', 'GRL', '304');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Grenada', 'GD', 'GRD', '308');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guadeloupe', 'GP', 'GLP', '312');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guam', 'GU', 'GUM', '316');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guatemala', 'GT', 'GTM', '320');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guernsey', 'GG', 'GGY', '831');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guinea', 'GN', 'GIN', '324');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guinea-Bissau', 'GW', 'GNB', '624');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Guyana', 'GY', 'GUY', '328');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Haiti', 'HT', 'HTI', '332');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD', '334');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Holy See (the)', 'VA', 'VAT', '336');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Honduras', 'HN', 'HND', '340');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Hong Kong', 'HK', 'HKG', '344');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Hungary', 'HU', 'HUN', '348');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Iceland', 'IS', 'ISL', '352');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('India', 'IN', 'IND', '356');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Indonesia', 'ID', 'IDN', '360');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Iran (Islamic Republic of)', 'IR', 'IRN', '364');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Iraq', 'IQ', 'IRQ', '368');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Ireland', 'IE', 'IRL', '372');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Isle of Man', 'IM', 'IMN', '833');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Israel', 'IL', 'ISR', '376');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Italy', 'IT', 'ITA', '380');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Jamaica', 'JM', 'JAM', '388');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Japan', 'JP', 'JPN', '392');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Jersey', 'JE', 'JEY', '832');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Jordan', 'JO', 'JOR', '400');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Kazakhstan', 'KZ', 'KAZ', '398');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Kenya', 'KE', 'KEN', '404');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Kiribati', 'KI', 'KIR', '296');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Korea (the Democratic People s Republic of)', 'KP', 'PRK', '408');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Korea (the Republic of)', 'KR', 'KOR', '410');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Kuwait', 'KW', 'KWT', '414');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Kyrgyzstan', 'KG', 'KGZ', '417');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Lao People s Democratic Republic (the)', 'LA', 'LAO', '418');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Latvia', 'LV', 'LVA', '428');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Lebanon', 'LB', 'LBN', '422');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Lesotho', 'LS', 'LSO', '426');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Liberia', 'LR', 'LBR', '430');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Libya', 'LY', 'LBY', '434');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Liechtenstein', 'LI', 'LIE', '438');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Lithuania', 'LT', 'LTU', '440');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Luxembourg', 'LU', 'LUX', '442');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Macao', 'MO', 'MAC', '446');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Madagascar', 'MG', 'MDG', '450');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Malawi', 'MW', 'MWI', '454');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Malaysia', 'MY', 'MYS', '458');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Maldives', 'MV', 'MDV', '462');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mali', 'ML', 'MLI', '466');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Malta', 'MT', 'MLT', '470');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Marshall Islands (the)', 'MH', 'MHL', '584');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Martinique', 'MQ', 'MTQ', '474');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mauritania', 'MR', 'MRT', '478');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mauritius', 'MU', 'MUS', '480');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mayotte', 'YT', 'MYT', '175');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mexico', 'MX', 'MEX', '484');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Micronesia (Federated States of)', 'FM', 'FSM', '583');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Moldova (the Republic of)', 'MD', 'MDA', '498');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Monaco', 'MC', 'MCO', '492');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mongolia', 'MN', 'MNG', '496');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Montenegro', 'ME', 'MNE', '499');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Montserrat', 'MS', 'MSR', '500');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Morocco', 'MA', 'MAR', '504');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Mozambique', 'MZ', 'MOZ', '508');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Myanmar', 'MM', 'MMR', '104');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Namibia', 'NA', 'NAM', '516');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Nauru', 'NR', 'NRU', '520');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Nepal', 'NP', 'NPL', '524');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Netherlands (the)', 'NL', 'NLD', '528');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('New Caledonia', 'NC', 'NCL', '540');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('New Zealand', 'NZ', 'NZL', '554');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Nicaragua', 'NI', 'NIC', '558');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Niger (the)', 'NE', 'NER', '562');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Nigeria', 'NG', 'NGA', '566');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Niue', 'NU', 'NIU', '570');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Norfolk Island', 'NF', 'NFK', '574');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Northern Mariana Islands (the)', 'MP', 'MNP', '580');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Norway', 'NO', 'NOR', '578');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Oman', 'OM', 'OMN', '512');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Pakistan', 'PK', 'PAK', '586');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Palau', 'PW', 'PLW', '585');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Palestine, State of', 'PS', 'PSE', '275');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Panama', 'PA', 'PAN', '591');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Papua New Guinea', 'PG', 'PNG', '598');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Paraguay', 'PY', 'PRY', '600');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Peru', 'PE', 'PER', '604');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Philippines (the)', 'PH', 'PHL', '608');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Pitcairn', 'PN', 'PCN', '612');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Poland', 'PL', 'POL', '616');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Portugal', 'PT', 'PRT', '620');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Puerto Rico', 'PR', 'PRI', '630');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Qatar', 'QA', 'QAT', '634');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Republic of North Macedonia', 'MK', 'MKD', '807');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Romania', 'RO', 'ROU', '642');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Russian Federation (the)', 'RU', 'RUS', '643');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Rwanda', 'RW', 'RWA', '646');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Réunion', 'RE', 'REU', '638');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Barthélemy', 'BL', 'BLM', '652');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA', '659');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Lucia', 'LC', 'LCA', '662');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Martin (French part)', 'MF', 'MAF', '663');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM', '666');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT', '670');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Samoa', 'WS', 'WSM', '882');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('San Marino', 'SM', 'SMR', '674');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Sao Tome and Principe', 'ST', 'STP', '678');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Saudi Arabia', 'SA', 'SAU', '682');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Senegal', 'SN', 'SEN', '686');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Serbia', 'RS', 'SRB', '688');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Seychelles', 'SC', 'SYC', '690');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Sierra Leone', 'SL', 'SLE', '694');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Singapore', 'SG', 'SGP', '702');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Sint Maarten (Dutch part)', 'SX', 'SXM', '534');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Slovakia', 'SK', 'SVK', '703');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Slovenia', 'SI', 'SVN', '705');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Solomon Islands', 'SB', 'SLB', '090');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Somalia', 'SO', 'SOM', '706');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('South Africa', 'ZA', 'ZAF', '710');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('South Sudan', 'SS', 'SSD', '728');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Spain', 'ES', 'ESP', '724');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Sri Lanka', 'LK', 'LKA', '144');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Sudan (the)', 'SD', 'SDN', '729');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Suriname', 'SR', 'SUR', '740');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM', '744');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Sweden', 'SE', 'SWE', '752');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Switzerland', 'CH', 'CHE', '756');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Syrian Arab Republic', 'SY', 'SYR', '760');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Taiwan (Province of China)', 'TW', 'TWN', '158');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Tajikistan', 'TJ', 'TJK', '762');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Tanzania, United Republic of', 'TZ', 'TZA', '834');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Thailand', 'TH', 'THA', '764');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Timor-Leste', 'TL', 'TLS', '626');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Togo', 'TG', 'TGO', '768');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Tokelau', 'TK', 'TKL', '772');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Tonga', 'TO', 'TON', '776');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Trinidad and Tobago', 'TT', 'TTO', '780');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Tunisia', 'TN', 'TUN', '788');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Turkey', 'TR', 'TUR', '792');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Turkmenistan', 'TM', 'TKM', '795');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Turks and Caicos Islands (the)', 'TC', 'TCA', '796');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Tuvalu', 'TV', 'TUV', '798');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Uganda', 'UG', 'UGA', '800');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Ukraine', 'UA', 'UKR', '804');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('United Arab Emirates (the)', 'AE', 'ARE', '784');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('United Kingdom of Great Britain and Northern Ireland (the)', 'GB', 'GBR', '826');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('United States Minor Outlying Islands (the)', 'UM', 'UMI', '581');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('United States of America (the)', 'US', 'USA', '840');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Uruguay', 'UY', 'URY', '858');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Uzbekistan', 'UZ', 'UZB', '860');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Vanuatu', 'VU', 'VUT', '548');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Venezuela (Bolivarian Republic of)', 'VE', 'VEN', '862');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Viet Nam', 'VN', 'VNM', '704');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Virgin Islands (British)', 'VG', 'VGB', '092');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Virgin Islands (U.S.)', 'VI', 'VIR', '850');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Wallis and Futuna', 'WF', 'WLF', '876');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Western Sahara', 'EH', 'ESH', '732');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Yemen', 'YE', 'YEM', '887');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Zambia', 'ZM', 'ZMB', '894');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Zimbabwe', 'ZW', 'ZWE', '716');
INSERT INTO recruitment.nationality (description, iso_2, iso_3, code) VALUES ('Åland Islands', 'AX', 'ALA', '248');
